### ISSUE TITLE
关于get_scores函数中avg参数的使用方法

### ISSUE THREAD

**Issue by huhk-sysu** [ShenDezhou/lawrouge#1]
您好！

首先感谢您编写的这个库，但我在使用方法上还有些不明白。

在ReadMe中您提供的示例选择了avg=2，而我查看源码时发现avg一共有0、1、2三种选项。我理解了其中avg=2的结果为avg=1的结果加权得到，但avg=0和avg=1的区别我还不太了解。能否为我说明一下它们分别是什么场景下使用？

![image](https://user-images.githubusercontent.com/14769033/103076615-18397200-4609-11eb-9b97-1a4f5078b432.png)
上图为我模拟的实验，我发现使用avg=1时，输出的recall值超过了1，这是怎么回事？

**Comment by ShenDezhou** [comment]
avg=0返回的是每对串的rouge得分，avg=1返回这些串评分的平均值。r大于1的问题我验证一下回复你。-------- 原始邮件 --------发件人： Pure White <notifications@github.com>日期： 2020年12月24日周四 下午4:59收件人： ShenDezhou/lawrouge <lawrouge@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [ShenDezhou/lawrouge] 关于get_scores函数中avg参数的使用方法 (#1)
您好！
首先感谢您编写的这个库，但我在使用方法上还有些不明白。
在ReadMe中您提供的示例选择了avg=2，而我查看源码时发现avg一共有0、1、2三种选项。我理解了其中avg=2的结果为avg=1的结果加权得到，但avg=0和avg=1的区别我还不太了解。能否为我说明一下它们分别是什么场景下使用？

上图为我模拟的实验，我发现使用avg=1时，输出的recall值超过了1，这是怎么回事？

**Comment by huhk-sysu** [comment]
谢谢，当前我只需要对一对串进行rouge评分，是否只需要用avg=0（然后取结果的列表的第0项）就可以了。

**Comment by ShenDezhou** [comment]
> 谢谢，当前我只需要对一对串进行rouge评分，是否只需要用avg=0（然后取结果的列表的第0项）就可以了。

为了Recall大于1的问题，专门发布了一版新的Readme，来解释这个问题。https://pypi.org/project/lawrouge/ 。

rouge = lawrouge.Rouge(exclusive=True) 
scores = rouge.get_scores(["他是清华大学计算机科学与技术系。计算机科学与技术专业。"], ["他是清华大学计算机科学与技术系。"],  avg=1) 
print(scores)

你的第二个问题还是要在构造时指定exclusive=True，并用avg=0。
